import 'dart:ui';

/// Model representing a block of text detected in a camera frame.
class DetectedTextModel {
  /// The original text recognized by the OCR engine.
  final String originalText;

  /// The confidence score of the recognition, from 0.0 to 1.0 (or percentage).
  final double confidence;

  /// The physical bounding box of the text block in the camera coordinate space.
  final Rect boundingBox;

  /// Time when the text was processed.
  final DateTime timestamp;

  /// The script identified by the Script Detection service (e.g., "Telugu", "Hindi").
  final String detectedScript;

  /// The transliterated text generated by the transliteration engine.
  final String transliteratedText;

  DetectedTextModel({
    required this.originalText,
    required this.confidence,
    required this.boundingBox,
    required this.timestamp,
    this.detectedScript = 'Unknown',
    this.transliteratedText = '',
  });

  /// Creates a copy of this object with updated fields.
  DetectedTextModel copyWith({
    String? originalText,
    double? confidence,
    Rect? boundingBox,
    DateTime? timestamp,
    String? detectedScript,
    String? transliteratedText,
  }) {
    return DetectedTextModel(
      originalText: originalText ?? this.originalText,
      confidence: confidence ?? this.confidence,
      boundingBox: boundingBox ?? this.boundingBox,
      timestamp: timestamp ?? this.timestamp,
      detectedScript: detectedScript ?? this.detectedScript,
      transliteratedText: transliteratedText ?? this.transliteratedText,
    );
  }

  @override
  String toString() {
    return 'DetectedTextModel(originalText: $originalText, confidence: $confidence, '
        'boundingBox: $boundingBox, script: $detectedScript, transliterated: $transliteratedText)';
  }
}
